ALTER TABLE usuario
ADD COLUMN ativo BOOLEAN DEFAULT TRUE;

ALTER TABLE tag
ADD COLUMN ativo BOOLEAN DEFAULT TRUE;

ALTER TABLE subtag
ADD COLUMN ativo BOOLEAN DEFAULT TRUE;

ALTER TABLE grupo_assignado
ADD COLUMN ativo BOOLEAN DEFAULT TRUE;

ALTER TABLE categoria
ADD COLUMN ativo BOOLEAN DEFAULT TRUE;